// Code generated by muxc. DO NOT EDIT.
// versions:
//   muxc v1.0.0
// source: muxc.yaml

package muxc

import (
	"net/http"

	"github.com/enolgor/muxc/examples/basic/controllers"
	"github.com/enolgor/muxc/examples/basic/handlers"
	"github.com/enolgor/muxc/examples/basic/middlewares"
)

func chain(f http.HandlerFunc, middlewares ...func(http.HandlerFunc) http.HandlerFunc) http.HandlerFunc {
	for _, m := range middlewares {
		f = m(f)
	}
	return f
}

func Middleware(m func(http.Handler) http.Handler) func(http.HandlerFunc) http.HandlerFunc {
	return func(next http.HandlerFunc) http.HandlerFunc {
		return m(next).ServeHTTP
	}
}

func ConfigureMux(mux *http.ServeMux, ctrl controllers.Controller) {
	acceptJson := Middleware(middlewares.SetHeader("Accept", "application/json"))
	contentJson := Middleware(middlewares.SetHeader("Content-Type", "application/json"))
	mux.Handle("GET /api/v1/pet", chain(
		handlers.ListPets(ctrl),
		contentJson,
		Middleware(middlewares.Logger),
		Middleware(middlewares.RequestID),
	))
	mux.Handle("GET /api/v1/pet/{id}", chain(
		handlers.ReadPet(ctrl),
		contentJson,
		Middleware(middlewares.Logger),
		Middleware(middlewares.RequestID),
	))
	mux.Handle("PUT /api/v1/pet", chain(
		handlers.CreatePet(ctrl),
		contentJson,
		acceptJson,
		Middleware(middlewares.Logger),
		Middleware(middlewares.RequestID),
	))
	mux.Handle("POST /api/v1/pet", chain(
		handlers.UpdatePet(ctrl),
		contentJson,
		Middleware(middlewares.Logger),
		Middleware(middlewares.RequestID),
	))
	mux.Handle("DELETE /api/v1/pet", chain(
		handlers.DeletePet(ctrl),
		Middleware(middlewares.Logger),
		Middleware(middlewares.RequestID),
	))
}
